Use CHL - extended
bountygiver/DetailedSoldierListWOTC pull request #5
Opened 2020-01-23 08:16 UTC by Xymanek

Extends upon #4 to also support https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/issues/651

Merging this PR should mark #4 as merged as well (as this one is based upon commits from that branch)

2020-02-09 21:29 UTC, bountygiver commented on DetailedSoldierListWOTC/Src/DetailedSoldierListWOTC/Classes/X2DownloadableContentInfo_DetailedSoldierListWOTC.uc
> +{
this crashes without CHL

you need a 
```
local X2StrategyElementTemplate VersionTemplate;

	VersionTemplate = class'X2StrategyElementTemplateManager'.static.GetStrategyElementTemplateManager().FindStrategyElementTemplate('CHXComGameVersion');
	if (VersionTemplate == none)
	{
		return false;
	}
```
before it

2020-02-09 21:33 UTC, bountygiver requested changes
CHL checking code did not include checks whether `CHXComGameVersionTemplate` exists or not

2020-02-09 22:20 UTC, Xymanek commented
`IsCHLMinVersionInstalled` assumes that the caller already checked for existence of CHL. `OnPreCreateTemplates` is an implicit CHL check as that method won't be called if CHL isn't loaded

2020-02-16 20:06 UTC, bountygiver approved these changes

2020-02-16 20:06 UTC, merged