Support custom displayed ranks for soldiers (#6)
bountygiver/DetailedSoldierListWOTC pull request #7
Opened 2020-03-15 17:23 UTC by pledbrook

The soldier list item `UpdateData()` function now checks whether the Community Highlander is installed, and if so, uses its functions to get the appropriate displayed rank and icon for the soldier.

I have tested this against Long War of the Chosen (with the community highlander) and vanilla WOTC (without the CHL).

Resolves #6.

2020-03-16 08:56 UTC, Xymanek approved these changes

2020-04-06 02:23 UTC, bountygiver requested changes
Put them in the same block as Line 346

2020-04-06 08:21 UTC, pledbrook commented
Code moved.

2020-04-21 08:39 UTC, pledbrook commented
@bountygiver Any chance you can take another look? Thanks.

2021-05-31 16:54 UTC, bountygiver approved these changes

2021-05-31 16:54 UTC, merged